theme: jekyll-theme-leap-day
title: Chromatic Solfege for Lilypond
description: This library allows you to write Lilypond scores with Chromatic-Solfege.
show_downloads: true
google_analytics: UA-159323195-1
