#!/bin/bash

# https://superuser.com/a/1288646
if [ "$0" = "$BASH_SOURCE" ]; then
    echo "Error: this script must be sourced."
    exit 1
fi

BASE_PATH=$(dirname $(realpath -e ${BASH_SOURCE}))
LIB="$BASE_PATH/lib/"
LIB_MOV="$BASE_PATH/lib-mov/"
LIB_LY="$BASE_PATH/lib-ly/"

echo "Initialized path : $BASE_PATH"
echo "lib     : $LIB"
echo "lib-mov : $LIB_MOV"
echo "lib-ly  : $LIB_LY"

if [[ ! -d $BASE_PATH ]]; then
    echo "error $BASE_PATH does not exist"
    return
elif [[ ! -d $LIB ]]; then
    echo "error $LIB does not exist"
    return
elif [[ ! -d $LIB_MOV ]];then
    echo "error $LIB_MOV does not exist"
    return
elif [[ ! -d $LIB_LY ]];then
    echo "error $LIB_LY does not exist"
    return
fi


export PATH="$PATH:$LIB:$LIB_MOV"
export LILYPOND_INCLUDE_DIR="$LIB_LY"

