#!/bin/bash

if type play > /dev/null; then
    # play -q -n synth 0.1 square 880 vol 0.5
    PITCH=$(echo "scale=10; 440 + 880 * ($RANDOM / 32767)" | bc)
    # PITCH=$(echo "scale=10; 440 + 2 ~ ($RANDOM / 32767)" | bc)
    play -q -n synth 0.1 square $PITCH vol 0.2 pad 0 20 reverb 100 0 100 100 4 &
else
    echo -ne '\007'
    echo "done"
fi


