#!/bin/bash

IN_FILES=();
OUT_FILE="$2"


while [[ 0 < "$#"  ]]; do 
    IN_FILES+=("$1")
    OUT_FILE="$1"
    shift;
done

unset 'IN_FILES[${#IN_FILES[@]}-1]'

function usage {
    echo "usage:";
    echo "${0##*/} [IN_DIR] [OUT_FILE]";
    exit;
}

if [[ "${#IN_FILES[@]}" == 0 ]]; then
    usage
    exit;
fi

# if [[ -f "$OUT_FILE" ]]; then
#     >&2 echo "$OUT_FILE already exists. Overwrite? (y/n)"
#     read i
#     if [[ ! $i="y" ]];then
#         exit 1;
#     fi
# fi

LIST_FILE="$OUT_FILE".txt

printf "%s\n" "${IN_FILES[@]}" | sort | { while read i; do echo "file '$i'"; done } > $LIST_FILE

ffmpeg -nostats -y -f concat -safe 0 -i "$LIST_FILE" -c copy "$OUT_FILE"


