#!/bin/bash

IN_DIR="$1"
IN_BACKGROUND_IMG="$2"
OUT_DIR="$3"

function usage {
    echo "usage:";
    echo "${0##*/} [IN_DIR] [IN_BACKGROUND_IMG] [OUT_DIR]";
    exit;
}

if [[ ! -d "$IN_DIR" ]]; then
    echo "IN_DIR does not exist"
    usage
elif [[ ! -f "$IN_BACKGROUND_IMG" ]]; then
    echo "IN_BACKGROUND_IMG does not exist"
    usage
elif [[ ! -d "$OUT_DIR" ]]; then
    echo "OUT_DIR does not exist"
    usage
fi


for IN_WAVE in "$IN_DIR"/*.wav
do
    echo $IN_WAVE
    wav2mp4 "$IN_WAVE" "$IN_BACKGROUND_IMG" "$OUT_DIR"
done

