#!/bin/bash

TEXT_FILE="$1"
TEMPLATE_DIR=$(dirname  $(realpath $BASH_SOURCE))
if [[ "$TEXT_FILE" =~ [0-9]+-Header.*$ ]]; then 
    TEMPLATE_FILE="$TEMPLATE_DIR/txtwav2mp4-header-template.svg"
elif [[ "$TEXT_FILE" =~ [0-9]+-Abstract.*$ ]]; then 
    TEMPLATE_FILE="$TEMPLATE_DIR/txtwav2mp4-header-template.svg"
else
    TEMPLATE_FILE="$TEMPLATE_DIR/txtwav2mp4-template.svg"
fi

SVG_FILE="$TEXT_FILE".svg
PNG_FILE="$SVG_FILE".png
PNG_TRIMMED_FILE="$SVG_FILE"-trimmed.png
IN_AUDIO="$2"
IN_BACKGROUND_IMG="$3"
OUT_FILE="$4"

REPLACEMENT_STRING="__REPLACE_THIS_TEXT__"

replace_text.js "$TEMPLATE_FILE" "$REPLACEMENT_STRING" "$TEXT_FILE" > "$SVG_FILE"
inkscape "$SVG_FILE" --export-png="$PNG_FILE"
#convert -trim "$PNG_FILE" "$PNG_TRIMMED_FILE"

convert "$PNG_FILE" \
    -gravity NORTH -background white -splice 0x5 -background black -splice 0x5 \
    -trim  +repage -chop 0x5  \
    -gravity SOUTH -background white -splice 0x5 -background black -splice 0x5 \
    -trim  +repage -chop 0x5  \
    "$PNG_TRIMMED_FILE"


pngwav2mp4 "$PNG_TRIMMED_FILE" "$IN_AUDIO"  "$IN_BACKGROUND_IMG" "$OUT_FILE"

