#!/bin/bash


mkdir -p out/wav/
rm -v out/wav/*

ALL=( out/*.wav )
cp -a "${ALL[@]}" out/wav
cd out/wav

function max_proc_count {
   while [ `jobs | wc -l` -gt $1 ]
   do
      sleep 0.1
   done
}

ALL=( *.wav )
for i in "${ALL[@]}"
do
	music2mp3 $i &
	max_proc_count 10
done;

max_proc_count 1

rm -r mp3
mkdir mp3
mv *.mp3 mp3

tar -czvf chromatic-`date +%Y%m%d`.tar.gz mp3

